/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        // EnteRent brand tokens
        indigo: { DEFAULT: '#1a237e', soft: '#e8eaf6' },
        teal: { DEFAULT: '#00695c', dark: '#004f45', soft: '#e0f2f1' },
        orange: { DEFAULT: '#e65100', dark: '#bf360c', soft: '#fff3e0' },
        cream: { DEFAULT: '#FAF9F5', dim: '#F5F4F0' },
        tint: { DEFAULT: '#EDF3FA', light: '#F3F7FC', border: '#D4E2F0', hover: '#E4EEF8', deep: '#E5EDF7' },
        muted: '#717B8A',
        ink: { DEFAULT: '#1a1c1c', soft: '#3e4946', mid: '#4A5568' },
        // Material 3 tokens from the Stitch exports
        primary: '#004f45',
        'on-primary': '#ffffff',
        'primary-container': '#00695c',
        'primary-fixed': '#a0f2e1',
        'on-primary-fixed': '#00201b',
        'on-primary-fixed-variant': '#005046',
        secondary: '#4c56af',
        'secondary-fixed': '#e0e0ff',
        'on-secondary-fixed': '#000767',
        tertiary: '#7e2900',
        'tertiary-container': '#a53800',
        'tertiary-fixed': '#ffdbcf',
        'on-tertiary-fixed': '#380d00',
        'on-tertiary-fixed-variant': '#802a00',
        error: '#ba1a1a',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        surface: '#faf9f9',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f4f3f3',
        'surface-container': '#eeeeed',
        'surface-container-high': '#e8e8e8',
        'surface-container-highest': '#e3e2e2',
        'on-surface': '#1a1c1c',
        'on-surface-variant': '#3e4946',
        outline: '#6e7976',
        'outline-variant': '#bec9c5',
        'inverse-surface': '#2f3131',
        'inverse-on-surface': '#f1f1f0',
      },
      fontFamily: {
        sans: ['"DM Sans"', 'system-ui', 'sans-serif'],
        serif: ['Newsreader', 'Georgia', 'serif'],
      },
      maxWidth: { app: '440px' },
      boxShadow: { xs: '0 1px 2px rgba(0,0,0,0.04)' },
    },
  },
  plugins: [],
};
